name: V3LD1N
description: A custom plugin for the V3LD1N server.
author: Ccosenza
main: com.v3ld1n.V3LD1N
softdepend: [WorldGuard, PermissionsEx]
version: "3.6.1"

commands:
  v3ld1nplugin:
    description: The main plugin command.
    aliases: [v3ld1np, vplugin, vp]
    usage: /<command> <arguments>
  faq:
    description: Answers frequently asked questions.
    aliases: [questions]
    usage: /<command> [question number]
  trail:
    description: Sets a particle trail for a player.
    aliases: [trails, particletrail, particletrails]
    usage: /<command> <particle|remove> [player]
  sethealth:
    description: Sets a player's health.
    aliases: [health]
    usage: /<command> <health> [player]
  setmaxhealth:
    description: Sets a player's maximum health.
    aliases: [maxhealth]
    usage: /<command> <health> [player]
  ratchetsbow:
    description: Sets your projectile for Ratchet's Bow.
    aliases: [rbow, rb]
    usage: /<command> <arrow|triplearrows|fireworkarrow|fireball|snowball|enderpearl|egg|witherskull|bluewitherskull>
  fireworkarrows:
    description: Sets your firework shape for firework arrows.
    aliases: [fireworkarrow, rbfw, fwa, fwas]
    usage: /<command> <ball|ball_large|star|creeper|burst>
  resourcepack:
    description: Downloads the server's resource packs.
    aliases: [pack, rp]
    usage: /<command> [resource pack]
  autoresourcepack:
    description: Automatically download a resource pack when you join the server.
    aliases: [autopack, autorp]
    usage: /<command> [resource pack]
  motd:
    description: Displays the login message.
    aliases: [vpmotd]
    usage: /<command> [player]
  nextsound:
    description: Plays the next sound for a sound task.
    aliases: [playnextsound, soundnext, snext]
    usage: /<command> [sound task]
  editsign:
    description: Changes the text on a sign.
    aliases: [signedit, changesign, es, se]
    usage: /<command> <set|add|remove> <line> <text ...>
  setfulltime:
    description: Sets the full time of the world you are in.
    aliases: [setftime, sfulltime]
    usage: /<command> <time>
  playanimation:
    description: Plays an animation on a player.
    aliases: [animation, playanim, anim]
    usage: /<command> <animation> [player]
  sidebarmessage:
    description: Broadcasts a message to the sidebar.
    aliases: [sbmessage, sbm, sbbroadcast]
    usage: /<command> <time> <title> <line1> [more lines] ...
  uuid:
    description: Sends a player's UUID in a chat message.
    aliases: [uniqueid]
    usage: /<command> [player]
  push:
    description: Pushes a player.
    aliases: [setvelocity]
    usage: /<command> <player> <speedX> <speedY> <speedZ> OR /<command> <player> <toPlayer> [speed]
  sethotbarslot:
    description: Sets a player's selected hotbar slot.
    aliases: [hotbarslot, setselectedslot]
    usage: /<command> <slot> [player]
  v3ld1nmotd:
    description: Adds, removes, and lists MOTDs.
    aliases: [vmotd]
    usage: /<command> <add|remove|list> <motd ...>
  actionbarmessage:
    description: Displays a message above the action bar.
    aliases: [abmessage, abm, abbroadcast]
    usage: /<command> all|<player> <message ...>
  report:
    description: Sends a report to the admins.
    aliases: [reports]
    usage: /<command> <player> <reason ...>
  timeplayed:
    description: Displays the amount of time a player has played.
    aliases: [playtime]
    usage: /<command> [player]
  playerlist:
    description: Sets the player list header and footer.
    usage: /<command> set <header> <footer> OR /<command> reset OR /<command> ping
  giveall:
    description: Gives the item you are holding to all players.
    usage: /<command>
  players:
    description: Player information command.
    aliases: [player]
    usage: /<command> <arguments>
  v3ld1nwarp:
    description: Adds, removes, and lists warps.
    aliases: [vwarp]
    usage: /<command> <add|remove> <warp> OR /<command> list
  ride:
    description: Right-click on an entity to ride it.
    aliases: [rideentity, entityride]
    usage: /<command>
  names:
    description: Displays information about player names.
    aliases: [name]
    usage: /<command> <playerName>
  playersay:
    description: Send a chat message as another player.
    aliases: [sayplayer, ps, psay]
    usage: /<command> <player> <message ...>
  sethunger:
    description: Sets a player's hunger, exhaustion, or saturation level.
    aliases: [hunger, sethungerlevel, setfood, setfoodlevel, foodlevel]
    usage: /<command> <hunger> <hunger|exhaustion|saturation> [player]
  damage:
    description: Damages a player.
    aliases: [hurt, dmg, removehealth]
    usage: /<command> <amount> [player]
  moneyitem:
    description: Creates a Vault money item.
    aliases: [mi, veldsitem, vi]
    usage: /<command> <amount>
  changelog:
    description: Shows the server changelog.
    aliases: [change, changes]
    usage: /<command> [log <change>]